// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGConstants
{
        public const string achievement_apprentice = "CgkIpIPf580dEAIQDA"; // <GPGSID>
        public const string achievement_top_ten = "CgkIpIPf580dEAIQCQ"; // <GPGSID>
        public const string leaderboard_most_touchdowns = "CgkIpIPf580dEAIQAA"; // <GPGSID>
        public const string achievement_enthusiast = "CgkIpIPf580dEAIQDQ"; // <GPGSID>
        public const string achievement_touchdown = "CgkIpIPf580dEAIQBg"; // <GPGSID>
        public const string package_name = "com.smd.runningback"; // <GPGSID>
        public const string achievement_supersonic = "CgkIpIPf580dEAIQFA"; // <GPGSID>
        public const string leaderboard_most_yards_gained = "CgkIpIPf580dEAIQAQ"; // <GPGSID>
        public const string achievement_guru = "CgkIpIPf580dEAIQDw"; // <GPGSID>
        public const string achievement_team_player = "CgkIpIPf580dEAIQFQ"; // <GPGSID>
        public const string achievement_boost = "CgkIpIPf580dEAIQEA"; // <GPGSID>
        public const string leaderboard_total_yards_gained = "CgkIpIPf580dEAIQAg"; // <GPGSID>
        public const string achievement_charged = "CgkIpIPf580dEAIQEg"; // <GPGSID>
        public const string achievement_reservation_for_6 = "CgkIpIPf580dEAIQCA"; // <GPGSID>
        public const string achievement_turbo = "CgkIpIPf580dEAIQEQ"; // <GPGSID>
        public const string achievement_novice = "CgkIpIPf580dEAIQCw"; // <GPGSID>
        public const string achievement_3_in_a_row = "CgkIpIPf580dEAIQBw"; // <GPGSID>
        public const string leaderboard_total_touchdowns = "CgkIpIPf580dEAIQAw"; // <GPGSID>
        public const string achievement_twenty = "CgkIpIPf580dEAIQCg"; // <GPGSID>
        public const string achievement_energized = "CgkIpIPf580dEAIQEw"; // <GPGSID>
        public const string achievement_professional = "CgkIpIPf580dEAIQDg"; // <GPGSID>

}

