// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGConstants
{
        public const string leaderboard_most_touchdowns = "CgkIpIPf580dEAIQAA"; // <GPGSID>
        public const string achievement_test4 = "CgkIpIPf580dEAIQCQ"; // <GPGSID>
        public const string leaderboard_total_yards_gained = "CgkIpIPf580dEAIQAg"; // <GPGSID>
        public const string package_name = "com.smd.runningback"; // <GPGSID>
        public const string leaderboard_most_yards_gained = "CgkIpIPf580dEAIQAQ"; // <GPGSID>
        public const string achievement_test = "CgkIpIPf580dEAIQBg"; // <GPGSID>
        public const string achievement_test2 = "CgkIpIPf580dEAIQBw"; // <GPGSID>
        public const string achievement_test3 = "CgkIpIPf580dEAIQCA"; // <GPGSID>
        public const string leaderboard_total_touchdowns = "CgkIpIPf580dEAIQAw"; // <GPGSID>
        public const string achievement_test6 = "CgkIpIPf580dEAIQCg"; // <GPGSID>

}

